using Content.Shared._Misfits.WastelandMap;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Misfits.WastelandMap;

[GenerateTypedNameReferences]
public sealed partial class MapPinWindow : DefaultWindow
{
    public event Action<string>? OnSubmit;

    public MapPinWindow()
    {
        RobustXamlLoader.Load(this);

        SubmitButton.OnPressed += _ => Submit();
        NameInput.OnTextEntered += _ => Submit();
        CancelButton.OnPressed += _ => Close();
    }

    private void Submit()
    {
        var name = NameInput.Text.Trim();
        if (name.Length == 0)
            return;

        OnSubmit?.Invoke(name);
        Close();
    }
}

[UsedImplicitly]
public sealed class MapPinBoundUserInterface : BoundUserInterface
{
    private MapPinWindow? _window;

    public MapPinBoundUserInterface(EntityUid owner, Enum uiKey) : base(owner, uiKey)
    {
    }

    protected override void Open()
    {
        base.Open();
        _window = this.CreateWindow<MapPinWindow>();
        _window.OnSubmit += name => SendMessage(new MapPinNameMessage(name));
    }
}
